apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vy1a0p95j-go 
  janus-idp.io/tekton: vy1a0p95j-go
  backstage.io/kubernetes-id: vy1a0p95j-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vy1a0p95j-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  