apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vy1a0p95j-go-gitops
  description: This is GitOps manifest for vy1a0p95j-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: vy1a0p95j-go
    janus-idp.io/tekton: vy1a0p95j-go
    backstage.io/kubernetes-id: vy1a0p95j-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vy1a0p95j-go
